global:
  scrape_interval: 5s  # Fetch metrics every 5 seconds

scrape_configs:
  - job_name: 'bentoml'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['bentoml:3000']
  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]  # Make sure it matches your container name

rule_files:
  - "alert_rules.yml"
