global:
  scrape_interval: 5s  # Fetch metrics every 5 seconds

scrape_configs:
  - job_name: 'bentoml'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['bentoml:3000']

  - job_name: 'movie_recommender'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['evidently:5000']  # Change 'evidently' to the name of the service running your API


