# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc

    - name: Configure DVC and pull data
      env:
        DVC_REMOTE_URL: ${{ secrets.DVC_REMOTE_URL }}
        DVC_ACCESS_KEY: ${{ secrets.DVC_ACCESS_KEY_ID }}
        DVC_SECRET_KEY: ${{ secrets.DVC_SECRET_ACCESS_KEY }}
      run: |
        dvc remote add origin s3://dvc --force
        dvc remote modify origin endpointurl $DVC_REMOTE_URL
        dvc remote default origin
        dvc remote modify origin --local access_key_id  $DVC_ACCESS_KEY
        dvc remote modify origin --local secret_access_key $DVC_SECRET_KEY 
        dvc pull

    # Data Splitting
    - name: Run Data Splitting
      run: python src/data/data_split.py

    # Grid Search for Best Model Parameters
    - name: Run Grid Search
      run: python src/models/model_grid_search.py

    # Model Training
    - name: Train Model
      run: python src/models/model_train.py

    # Model Evaluation
    - name: Evaluate Model
      run: python src/models/model_evaluate.py

